config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :posts do
    member do
      get :toggle_status
    end
  end
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'show_portfolio'

  mount ActionCable.server => '/cable'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }
  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
    where(subtitle: 'Angular')
  end

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails') }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :show, :update, :destroy]
  layout 'portfolio'
  access all: [:show, :index, :angular], site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true
  end

  def angular
    @portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def edit
  end

  def show
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Portfolio was sucessfully removed.' }
    end
  end

  private

    def portfolio_params
      params.require(:portfolio).permit(
        :title,
        :subtitle,
        :body,
        :main_image,
        :thumb_image,
        technologies_attributes: [:id, :name, :_destroy], )
    end

    def set_portfolio_item
      @portfolio_item = Portfolio.find(params[:id])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img.file
      img
    elsif type == :thumb
      image_generator height: '350', width: '200'
    elsif type == :main
      image_generator height: '600', width: '400'
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio_item) do |form| %>
  <% if portfolio_item.errors.any? %>
      <%= gritter array_to_ul(post.errors.full_messages).full_messages, title: pluralize(portfolio_item.errors.count, "error") %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.text_field :title, id: :portfolio_title, class: 'form-control', placeholder: 'Title' %>
      </div>

      <div class="form-group">
        <%= form.text_field :subtitle, id: :portfolio_subtitle, class: 'form-control', placeholder: 'Subtitle' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a Main Image <%= form.file_field :main_image, style: 'display:none;' %>
        </label>
        <span class="file-name"></span>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a Thumb Image <%= form.file_field :thumb_image, style: 'display:none;' %>
        </label>
        <span class="file-name"></span>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.text_area :body, id: :portfolio_body, class: 'form-control', rows: 12, placeholder: 'Content' %>
      </div>
    </div>
    <div class="col-md-12">
      <hr>
      <h3>Technologies used</h3>
      <div class="nested-fields">
        <%= form.fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields', f: technology_form %>
        <% end %>
        <div>
          <%= link_to_add_association 'Add Technology', form, :technologies %>
        </div>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Save Portfolio Item', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="card" data-id="<%= portfolio_item.id %>">
  <%= image_tag portfolio_img(portfolio_item.thumb_image, :thumb) %>
  <p class="card-text">
    <%= link_to portfolio_item.title, show_portfolio_path(portfolio_item) %>
    <%= portfolio_item.subtitle %>
  </p>
</div>

app/views/portfolios/_portfolio_options.html.erb
<% if logged_in? :site_admin %>
<div class="portfolio-options">
  <%= link_to 'Edit', edit_portfolio_path(portfolio_item) %> |
  <%= link_to 'Destroy', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<% end %>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group">
  <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
  <%= link_to_remove_association 'Remove', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Portfolio Items</h1>
<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>
<div>
  <% @portfolio_items.each do |item| %>
  <div>
    <h2><%= link_to item.title, show_portfolio_path(item) %></h2>
    <div><%= link_to "Edit", edit_portfolio_path(item) if logged_in?(:site_admin) %> | <%= link_to "Delete", item, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></div>
    <div><%= item.subtitle %></div>
    <div><%= item.body %></div>
    <%=  image_tag item.thumb_image if item.thumb_image? %>
  </div>
  <% end %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
        <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.main_image, :main), width: '100%' %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <%= render 'portfolio_options', portfolio_item: @portfolio_item %>
      <em><%= @portfolio_item.subtitle %></em>
      <p><%= @portfolio_item.body %></p>

      <h2>Technologies used:</h2>
      <% @portfolio_item.technologies.each do |technology| %>
      <p><%= technology.name %></p>
      <% end %>
    </div>
  </div>
</div>