config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :posts do
    member do
      get :toggle_status
    end
  end
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'show_portfolio'

  mount ActionCable.server => '/cable'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p>
      <%= copyright_helper %>
    </p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Nathan Schulzke</h3>
    <nav class="nav nav-masthead">
      <%= nav_helper do |title, link|
        link_to title, link, class: "nav-link #{active? link}"
      end %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_helper %>
  </p>
</footer>

app/views/shared/_blog_header.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <%= link_to 'New Post', new_post_path if logged_in?(:site_admin) %>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav" id="blog-masthead">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container">
    <%= link_to "Nathan Schulzke", root_path, class: 'navbar-brand' %>
    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper do |title, link|
          content_tag :li, link_to(title, link, class: "nav-link #{active? link}")
        end %>
        <%= content_tag :li, login_helper('nav-link') %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
  <div class="sidebar-module">
    <h4>Topics</h4>
    <ol class="list-unstyled">
      <% @sidebar_topics.each do |topic| %>
      <li><%= link_to "#{topic.title} (#{topic.posts.count})", topic %></li>
      <% end %>
    </ol>
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav>
  <div>
    <%= link_to "Home", root_path %>
    <%= link_to "About", about_path %>
    <%= link_to "Contact", contact_path %>
    <%= link_to "Blog", posts_path %>
    <%= link_to "Portfolio", portfolios_path %>
  </div>
  <div>
    <%= login_helper %>
  </div>
</nav>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "Back to #{@portfolio_items ? "Top" : "Gallery"}", portfolios_path %>
    </p>
    <p><%= copyright_helper %></p>
  </div>
</footer>

app/views/shared/_portfolio_header.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Album example</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <%= link_to 'Learn More About Me', about_path, class: 'btn btn-primary' %>
      <%= link_to 'Visit My Blog', posts_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper do |title, link|
            content_tag :li, link_to(title, link, class: "text-white")
          end %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Nathan Schulzke</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>

app/views/shared/_post_options.html.erb
<% if logged_in? :site_admin %>
<div class="post-options">
  <%= link_to fa_icon('file-text'), toggle_status_post_path(post), style: post_status_style(post) %> |
  <%= link_to fa_icon('pencil-square-o'), edit_post_path(post) %> |
  <%= link_to fa_icon('trash-o'), post, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<% end %>